### ISSUE TITLE
it notice me the command not work . but i try it on linux it's works,can anyone help this

### ISSUE THREAD

**Issue by ruhong65** [PHP-FFMpeg/PHP-FFMpeg#371]
| Q              | A
| -------------- | ---
| Bug?           | mayybe
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | 2.6.8
| OS             | centos7 

i was move my code to server ,and it's not work 

Fatal error: Uncaught exception 'Alchemy\BinaryDriver\Exception\ExecutionFailureException' with message 'ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' '/var/www/html/DYT/trunk/input.flac' '-threads' '12' '-acodec' 'libmp3lame' '-b:a' '300k' '-ac' '2' '/var/www/html/DYT/trunk/300.mp3'' in /var/www/html/DYT/trunk/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 Stack trace: #0 /var/www/html/DYT/trunk/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffmpe...') #1 /var/www/html/DYT/trunk/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) #2 /var/www/html/DYT/trunk/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array) #3 /var/www/h in /var/www/html/DYT/trunk/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Audio.php on line 100

but when i use the command 
/usr/bin/ffmpeg -y -i /var/www/html/DYT/trunk/input.flac -threads 12 -acodec libmp3lame -b:a 300k -ac 2 /var/www/html/DYT/trunk/300.mp3
it's works .

my code is 

	function testff(){
	

		$ffmpeg = FFMpeg\FFMpeg::create(array(
		    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
		    'ffprobe.binaries' => '/usr/bin/ffprobe',
		    'timeout'          => 3600, // The timeout for the underlying process
		    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
		), $logger);
		

		$audio = $ffmpeg->open('/var/www/html/DYT/trunk/input.flac');

		$format = new FFMpeg\Format\Audio\Mp3();

		$format->on('progress', function ($audio, $format, $percentage) {
		    echo "$percentage % transcoded";
		});

		$format
		    ->setAudioChannels(2)
		    ->setAudioKiloBitrate(300);

		$audio->save($format, '/var/www/html/DYT/trunk/300.mp3');
	}

**Comment by jens1o** [comment]
Can you check your php-user do have permission to execute ffmpeg and on these directories?

**Comment by ruhong65** [comment]
thanks @jens1o  I add the permission and it's works .

**Comment by jens1o** [comment]
@ruhong65 Could you close this issue, please?
