### ISSUE TITLE
ffprobe failed to execute command '/usr/bin/ffprobe' '-help' '-loglevel' 'quiet'

### ISSUE THREAD

**Issue by xvrzhao** [PHP-FFMpeg/PHP-FFMpeg#501]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | 0.11.0
| FFmpeg Version | 0.10.16
| OS             | CentOS 6.9

#### Actual Behavior

I just want to extract an image from video, but the code throw the exception following:
```
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffprobe failed to execute command '/usr/bin/ffprobe' '-help' '-loglevel' 'quiet' in /home/www/xuanping/http-server/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:100 
Stack trace: 
#0 /home/www/xuanping/http-server/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(''/usr/bin/ffpro...') 
#1 /home/www/xuanping/http-server/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false) 
#2 /home/www/xuanping/http-server/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, NULL) 
#3 /home/www/xuanping/http-server/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\BinaryDriver\ in /home/www/xuanping/http-server/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php on line 63
```

This is my code:
```
$ffmpeg = FFMpeg::create([
                    'ffmpeg.binaries' => '/usr/bin/ffmpeg',
                    'ffprobe.binaries' => '/usr/bin/ffprobe',
                    'timeout' => 3600, // The timeout for the underlying process
                    'ffmpeg.threads' => 12,   // The number of threads that FFMpeg should use
                ]);

                $video = $ffmpeg->open(/* my video's realpath*/);
                $frame = $video->frame(TimeCode::fromSeconds(1)); // extract the image
                $frame->save(/*the image save realpath*/);
```

**Comment by xvrzhao** [comment]
And I executed it in CLI:
```
[root@localhost ~]# /usr/bin/ffprobe -help -loglevel quiet
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

Main options:
-L                  show license
-h                  show help
-?                  show help
-help               show help
--help              show help
-version            show version
-formats            show available formats
-codecs             show available codecs
-bsfs               show available bit stream filters
-protocols          show available protocols
-filters            show available filters
-pix_fmts           show available pixel formats
-sample_fmts        show available audio sample formats
-loglevel loglevel  set libav* logging level
-v loglevel         set libav* logging level
-debug flags        set debug flags
-report             generate a report
-max_alloc bytes    set maximum size of a single allocated block
-f format           force format
-unit               show unit of the displayed values
-prefix             use SI prefixes for the displayed values
-byte_binary_prefix  use binary prefixes for byte units
-sexagesimal        use sexagesimal format HOURS:MM:SS.MICROSECONDS for time units
-pretty             prettify the format of displayed values, make it more human readable
-print_format format  set the output printing format (available formats are: default, compact, csv, json, xml)
-show_error         show probing error
-show_format        show format/container info
-show_frames        show frames info
-show_packets       show packets info
-show_streams       show streams info
-show_program_version  show ffprobe version
-show_library_versions  show library versions
-show_versions      show program and library versions
-show_private_data  show private data
-private            same as show_private_data
-default            generic catch all option
-i input_file       read specified file

AVFormatContext AVOptions:
-probesize         <int>   .D... set probing size
-fflags            <flags> ED...
   ignidx                  .D... ignore index
   genpts                  .D... generate pts
   nofillin                .D... do not fill in missing values that can be exactly calculated
   noparse                 .D... disable AVParsers, this needs nofillin too
   igndts                  .D... ignore dts
   discardcorrupt          .D... discard corrupted frames
   sortdts                 .D... try to interleave outputted packets by dts
   keepside                .D... dont merge side data
-analyzeduration   <int>   .D... how many microseconds are analyzed to estimate duration
-cryptokey         <binary> .D... decryption key
-indexmem          <int>   .D... max memory used for timestamp index (per stream)
-rtbufsize         <int>   .D... max memory used for buffering real-time frames
-fdebug            <flags> ED... print specific debug info
   ts                      ED...
-max_delay         <int>   ED... maximum muxing or demuxing delay in microseconds
-fpsprobesize      <int>   .D... number of frames used to probe fps
-f_err_detect      <flags> .D... set error detection flags (deprecated; use err_detect, save via avconv)
   crccheck                .D... verify embedded CRCs
   bitstream               .D... detect bitstream specification deviations
   buffer                  .D... detect improper bitstream length
   explode                 .D... abort decoding on minor error detection
   careful                 .D... consider things that violate the spec and have not been seen in the wild as errors
   compliant               .D... consider all spec non compliancies as errors
   aggressive              .D... consider things that a sane encoder shouldnt do as an error
-err_detect        <flags> .D... set error detection flags
   crccheck                .D... verify embedded CRCs
   bitstream               .D... detect bitstream specification deviations
   buffer                  .D... detect improper bitstream length
   explode                 .D... abort decoding on minor error detection
   careful                 .D... consider things that violate the spec and have not been seen in the wild as errors
   compliant               .D... consider all spec non compliancies as errors
   aggressive              .D... consider things that a sane encoder shouldnt do as an error

AVI demuxer AVOptions:
-use_odml          <int>   .D... use odml index

cavsvideo demuxer AVOptions:
-framerate         <string> .D...

dirac demuxer AVOptions:
-framerate         <string> .D...

dnxhd demuxer AVOptions:
-framerate         <string> .D...

g729 demuxer AVOptions:
-bit_rate          <int>   .D...

gsm demuxer AVOptions:
-sample_rate       <int>   .D...

h261 demuxer AVOptions:
-framerate         <string> .D...

h263 demuxer AVOptions:
-framerate         <string> .D...

h264 demuxer AVOptions:
-framerate         <string> .D...

image2 demuxer AVOptions:
-pixel_format      <string> .D...
-video_size        <string> .D...
-framerate         <string> .D...
-loop              <int>   .D...

image2pipe demuxer AVOptions:
-pixel_format      <string> .D...
-video_size        <string> .D...
-framerate         <string> .D...
-loop              <int>   .D...

ingenient demuxer AVOptions:
-framerate         <string> .D...

m4v demuxer AVOptions:
-framerate         <string> .D...

mjpeg demuxer AVOptions:
-framerate         <string> .D...

mov,mp4,m4a,3gp,3g2,mj2 AVOptions:
-use_absolute_path <int>   .DV.. allow using absolute path when opening alias, this is a possible security issue

mpegtsraw demuxer AVOptions:
-compute_pcr       <int>   .D... Compute exact PCR for each transport stream packet.

mpegvideo demuxer AVOptions:
-framerate         <string> .D...

alaw demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

mulaw demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

f64be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

f64le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

f32be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

f32le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s32be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s32le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s24be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s24le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s16be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s16le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

s8 demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u32be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u32le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u24be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u24le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u16be demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u16le demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

u8 demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

rawvideo demuxer AVOptions:
-video_size        <string> .D... A string describing frame size, such as 640x480 or hd720.
-pixel_format      <string> .D...
-framerate         <string> .D...

RTP demuxer AVOptions:
-rtp_flags         <flags> .D... RTP flags
   filter_src              .D... Only receive packets from the negotiated peer IP

RTSP demuxer AVOptions:
-initial_pause     <int>   .D... Don't start playing the stream immediately
-rtsp_transport    <flags> ED... RTSP transport protocols
   udp                     ED... UDP
   tcp                     ED... TCP
   udp_multicast           .D... UDP multicast
   http                    .D... HTTP tunneling
-rtsp_flags        <flags> .D... RTSP flags
   filter_src              .D... Only receive packets from the negotiated peer IP
-allowed_media_types <flags> .D... Media types to accept from the server
   video                   .D... Video
   audio                   .D... Audio
   data                    .D... Data
-min_port          <int>   ED... Minimum local UDP port
-max_port          <int>   ED... Maximum local UDP port

sbg_demuxer AVOptions:
-sample_rate       <int>   .D...
-frame_size        <int>   .D...
-max_file_size     <int>   .D...

SDP demuxer AVOptions:
-sdp_flags         <flags> .D... SDP flags
   filter_src              .D... Only receive packets from the negotiated peer IP
-allowed_media_types <flags> .D... Media types to accept from the server
   video                   .D... Video
   audio                   .D... Audio
   data                    .D... Data

TTY demuxer AVOptions:
-chars_per_frame   <int>   .D...
-video_size        <string> .D... A string describing frame size, such as 640x480 or hd720.
-framerate         <string> .D...

vc1 demuxer AVOptions:
-framerate         <string> .D...

WAV demuxer AVOptions:
-ignore_length     <int>   .D... Ignore length

ALSA demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

DV1394 indev AVOptions:
-standard          <int>   .D...
   PAL                     .D...
   NTSC                    .D...
-channel           <int>   .D...

fbdev indev AVOptions:
-framerate         <string> .D...

lavfi indev AVOptions:
-graph             <string> .D... Libavfilter graph
-dumpgraph         <string> .D... Dump graph to stderr

openal AVOptions:
-channels          <int>   .D... set number of channels
-sample_rate       <int>   .D... set sample rate
-sample_size       <int>   .D... set sample size
-list_devices      <int>   .D... list available devices
   true                    .D...
   false                   .D...

OSS demuxer AVOptions:
-sample_rate       <int>   .D...
-channels          <int>   .D...

Pulse demuxer AVOptions:
-server            <string> .D... pulse server name
-name              <string> .D... application name
-stream_name       <string> .D... stream description
-sample_rate       <int>   .D... sample rate in Hz
-channels          <int>   .D... number of audio channels
-frame_size        <int>   .D... number of bytes per frame
-fragment_size     <int>   .D... buffering size, affects latency and cpu usage

V4L2 indev AVOptions:
-standard          <string> .D... TV standard, used only by analog frame grabber
-channel           <int>   .D... TV channel, used only by frame grabber
-video_size        <string> .D... A string describing frame size, such as 640x480 or hd720.
-pixel_format      <string> .D... Preferred pixel format
-input_format      <string> .D... Preferred pixel format (for raw video) or codec name
-framerate         <string> .D...
-list_formats      <int>   .D... List available formats and exit
   all                     .D... Show all available formats
   raw                     .D... Show only non-compressed formats
   compressed              .D... Show only compressed formats

V4L indev AVOptions:
-standard          <int>   .D...
   PAL                     .D...
   SECAM                   .D...
   NTSC                    .D...

X11grab indev AVOptions:
-video_size        <string> .D... A string describing frame size, such as 640x480 or hd720.
-framerate         <string> .D...
-draw_mouse        <int>   .D... Draw the mouse pointer.
-follow_mouse      <int>   .D... Move the grabbing region when the mouse pointer reaches within specified amount of pixels to the edge of region.
   centered                .D... Keep the mouse pointer at the center of grabbing region when following.
-show_region       <int>   .D... Show the grabbing region.

libcdio indev AVOptions:
-speed             <int>   .D... Drive reading speed.
-paranoia_mode     <flags> .D... Error recovery mode.
   verify                  .D... Verify data integrity in overlap area
   overlap                 .D... Perform overlapped reads.
   neverskip               .D... Do not skip failed reads.

libdc1394 indev AVOptions:
-video_size        <string> .D... A string describing frame size, such as 640x480 or hd720.
-pixel_format      <string> .D...
-framerate         <string> .D...

dv AVOptions:

GIF muxer AVOptions:

GXF muxer AVOptions:

image2 muxer AVOptions:

ipod muxer AVOptions:

ismv muxer AVOptions:

LATM/LOAS muxer AVOptions:

mov muxer AVOptions:

MP3 muxer AVOptions:

mp4 muxer AVOptions:

mpeg muxer AVOptions:

vcd muxer AVOptions:

dvd muxer AVOptions:

svcd muxer AVOptions:

vob muxer AVOptions:

MPEGTS muxer AVOptions:

mxf AVOptions:

mxf_d10 AVOptions:

Ogg muxer AVOptions:

psp muxer AVOptions:

RTP muxer AVOptions:

RTSP muxer AVOptions:
-initial_pause     <int>   .D... Don't start playing the stream immediately
-rtsp_transport    <flags> ED... RTSP transport protocols
   udp                     ED... UDP
   tcp                     ED... TCP
   udp_multicast           .D... UDP multicast
   http                    .D... HTTP tunneling
-rtsp_flags        <flags> .D... RTSP flags
   filter_src              .D... Only receive packets from the negotiated peer IP
-allowed_media_types <flags> .D... Media types to accept from the server
   video                   .D... Video
   audio                   .D... Audio
   data                    .D... Data
-min_port          <int>   ED... Minimum local UDP port
-max_port          <int>   ED... Maximum local UDP port

segment muxer AVOptions:

spdif AVOptions:

tg2 muxer AVOptions:

tgp muxer AVOptions:

WAV muxer AVOptions:

sdl outdev AVOptions:

```

**Comment by jens1o** [comment]
That's strange, could you please verify that the user hosting the php process has enough permissions to execute files and open new processes?

**Comment by xvrzhao** [comment]
Yes, and I guess that is due to permission, I will check and verify that and reply you when I back to company next Monday. Thank you !

**Comment by jens1o** [comment]
Okay, then it's most likely that the user may not open new processes.

**Comment by xvrzhao** [comment]
Still throwed the exception with the same info after installing a new version of ffprobe, why? 

And what's the mean of new processes you said ?

**Comment by jens1o** [comment]
We still use `ffprobe` and `ffmpeg` under the hood and open new processes to get the output of it. This library is bascially a wrapper, so you do not need to create the command yourself, but we're managing it under-the-hood.

**Comment by xvrzhao** [comment]
I have fixed the problem, the arch-criminal is the libs dependencies of ffmpeg is too old.

**Comment by jens1o** [comment]
Thanks for reaching back!

**Comment by azaddeveloper** [comment]
@xvrzhao How have you corrected this problem, please explain because I'm facing  same problem
