### ISSUE TITLE
Error in php 7

### ISSUE THREAD

**Issue by hamedmoody** [PHP-FFMpeg/PHP-FFMpeg#516]
when run php scrips with php 5.6 its work but not work in php 7:
<br />
<b>Fatal error</b>:  Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in D:\xampp\htdocs\ffmeg\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php:160
Stack trace:
#0 D:\xampp\htdocs\ffmeg\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration))
#1 D:\xampp\htdocs\ffmeg\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFProbe.php(226): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL)
#2 D:\xampp\htdocs\ffmeg\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\FFMpeg.php(117): FFMpeg\FFProbe::create(Array, NULL, Object(Doctrine\Common\Cache\ArrayCache))
#3 D:\xampp\htdocs\ffmeg\index.php(6): FFMpeg\FFMpeg::create()
#4 {main}

Next FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFProbe in D:\xampp\htdocs\ffmeg\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php:50
Stack trace:
#0 D:\xampp\h in <b>D:\xampp\htdocs\ffmeg\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Driver\FFProbeDriver.php</b> on line <b>50</b><br />

**Comment by hamedmoody** [comment]
sorry
i set below code and then worked:
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/opt/local/ffmpeg/bin/ffmpeg',
    'ffprobe.binaries' => '/opt/local/ffmpeg/bin/ffprobe',
    'timeout'          => 3600, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
), $logger);
