### ISSUE TITLE
Unable to remove all the files

### ISSUE THREAD

**Issue by shellus** [PHP-FFMpeg/PHP-FFMpeg#608]
| Q              | A
| -------------- | ---
| Bug?           | ?
| OS             | windows10

```
[2018-11-05 04:00:38] local.ERROR: Unable to remove all the files {"exception":"[object] (Neutron\\TemporaryFilesystem\\IOException(code: 0): Unable to remove all the files at C:\\www\\s-video\\vendor\
eutron\\temporary-filesystem\\src\\Neutron\\TemporaryFilesystem\\Manager.php:152, Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Failed to remove file \"C:\\Users\\shellus\\AppData\\Local\\Temp\\ffmpeg-passes5bdfbf39ca869px7hk\\pass-5bdfbf39ca9d8-0.log\": unlink(C:\\Users\\shellus\\AppData\\Local\\Temp\\ffmpeg-passes5bdfbf39ca869px7hk\\pass-5bdfbf39ca9d8-0.log): Resource temporarily unavailable. at C:\\www\\s-video\\vendor\\symfony\\filesystem\\Filesystem.php:184)
[stacktrace]
#0 C:\\www\\s-video\\vendor\
eutron\\temporary-filesystem\\src\\Neutron\\TemporaryFilesystem\\Manager.php(118): Neutron\\TemporaryFilesystem\\Manager->cleanScope('ffmpeg-passes5b...', true)
#1 C:\\www\\s-video\\vendor\\php-ffmpeg\\php-ffmpeg\\src\\FFMpeg\\Media\\AbstractVideo.php(103): Neutron\\TemporaryFilesystem\\Manager->clean('ffmpeg-passes5b...')
#2 C:\\www\\s-video\\app\\Jobs\\ConversionMp4Job.php(58): FFMpeg\\Media\\AbstractVideo->save(Object(FFMpeg\\Format\\Video\\X264), 'D:\\\\s_video_root...')
#3 [internal function]: App\\Jobs\\ConversionMp4Job->handle()
#4 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#5 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#9 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\ConversionMp4Job))
#10 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ConversionMp4Job))
#11 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\ConversionMp4Job), false)
#13 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Jobs\\Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#14 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(327): Illuminate\\Queue\\Jobs\\Job->fire()
#15 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#16 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(230): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#17 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(102): Illuminate\\Queue\\Worker->runNextJob('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#18 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#19 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#20 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#21 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#25 C:\\www\\s-video\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#26 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 C:\\www\\s-video\\vendor\\symfony\\console\\Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 C:\\www\\s-video\\vendor\\symfony\\console\\Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 C:\\www\\s-video\\vendor\\symfony\\console\\Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 C:\\www\\s-video\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 C:\\www\\s-video\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 {main}
"} 
```
Obviously, the problem is: `vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php(103)`
```php
$this->fs->clean($this->fsId);
```

This may be a bug in the eutron/temporary-filesystem package, or it may be a PHP-FFMpeg/PHP-FFMpeg error. Can anyone tell me how to fix it?

**Comment by jens1o** [comment]
I don't think it is a bug. It should be able to clear the directory. Can you make sure it has permissions to do that? I'm not that familiar with permissions on Windows, though, so I cannot give you exact steps. :/
