### ISSUE TITLE
cannot find executable ffprobe

### ISSUE THREAD

**Issue by nerotiger** [PHP-FFMpeg/PHP-FFMpeg#659]
> Notice: Undefined variable: logger in ./php_ffmpeg/PHP-FFMpeg/a.php on line 7
> 
> bool(true)
> bool(true)
> 
> ------------------
> string(25) "/data0/ffmpeg/bin/ffprobe"
> 
> bool(true)
> bool(true)
> 
> ------------------
> string(24) "/data0/ffmpeg/bin/ffmpeg"
> 
> Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in ./php_ffmpeg/PHP-FFMpeg/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:164
> Stack trace:
> #0 ./php_ffmpeg/PHP-FFMpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration))
> #1 ./php_ffmpeg/PHP-FFMpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(226): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL)
> #2 ./php_ffmpeg/PHP-FFMpeg/a.php(13): FFMpeg\FFProbe::create()
> #3 {main}
> 
> Next FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFProbe in ./php_ffmpeg/PHP-FFMpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php:50
> Stack trace:
> #0 ./php_ffmpeg/PHP-FFMpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(226): FFMpeg\Driver\ in ./php_ffmpeg/PHP-FFMpeg/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php on line 50

```
143     public static function load($binaries, LoggerInterface $logger = null, $configuration = array())
144     {
145         $finder = new ExecutableFinder();
146         $binary = null;
147         $binaries = is_array($binaries) ? $binaries : array($binaries);
148 
149         foreach ($binaries as $candidate) {
150             if (file_exists($candidate) && is_executable($candidate)) {
151 var_dump(file_exists($candidate));
152 var_dump(is_executable($candidate));
153 echo "\n------------------\n";
154                 $binary = $candidate;
155 var_dump($binary);
156                 break;
157             }
158             if (null !== $binary = $finder->find($candidate)) {
159                 break;
160             }
161         }
162 
163         if (null === $binary) {
164             throw new ExecutableNotFoundException(sprintf(
165                 'Executable not found, proposed : %s', implode(', ', $binaries)
166             ));
167         }
```

**Comment by nerotiger** [comment]
PHP-FFMpeg>$ ll /data0/ffmpeg/bin/
```
total 912
drwxr-xr-x  5 root  admin     160 Jun 19 03:10 .
drwxr-xr-x  6 root  admin     192 Jun 19 03:10 ..
-rwxr-xr-x  1 root  admin  227440 Jun 19 03:10 ffmpeg
-rwxr-xr-x  1 root  admin  113196 Jun 19 03:10 ffplay
-rwxr-xr-x  1 root  admin  121212 Jun 19 03:10 ffprobe

```

**Comment by nerotiger** [comment]
how comes ffmpeg working but ffprobe not... as they stay all together along.

**Comment by nerotiger** [comment]
wrong call.
