### ISSUE TITLE
Process must be started before calling getErrorOutput

### ISSUE THREAD

**Issue by thinker2013** [PHP-FFMpeg/PHP-FFMpeg#665]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Windows 7

I use wampserver for run it in develop machine. but some errors occured. os is win7.

require 'autoload.php';

$ffmpeg = FFMpeg\FFMpeg::create();
$default = ini_get('max_execution_time');
//var_dump($ffmpeg);
$video = $ffmpeg->open('D:/test.mp4');
var_dump($video);
$video
    ->filters()
    ->resize(new FFMpeg\Coordinate\Dimension(320, 240))
    ->synchronize();
$video
    ->frame(FFMpeg\Coordinate\TimeCode::fromSeconds(40))
    ->save('frame23.jpg');
$video
    ->save(new FFMpeg\Format\Video\X264(), 'export-x264.mp4')
    ->save(new FFMpeg\Format\Video\WMV(), 'export-wmv.wmv')
    ->save(new FFMpeg\Format\Video\WebM(), 'export-webm.webm');

Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\LogicException' with message 'Process must be started before calling getErrorOutput.' in G:\FFmpeg\vendor\symfony\process\Process.php on line 1690

**Comment by jens1o** [comment]
Please give us the stacktrace. :)

**Comment by danieltrolezi** [comment]
Same thing here... My stacktrace:

`/vendor/lakshmaji/thumbnail/src/[2020-08-11 12:48:20] homolog.ERROR: Process must be started before calling "getErrorOutput()". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\LogicException(code: 0): Process must be started before calling \"getErrorOutput()\". at /var/www/homolog-ws-sts.midia.zone/vendor/symfony/process/Process.php:1569
#0 /var/www/homolog-ws-sts.midia.zone/vendor/symfony/process/Process.php(1365): Symfony\\Component\\Process\\Process->requireProcessIsStarted('getErrorOutput')
#1 /var/www/homolog-ws-sts.midia.zone/vendor/symfony/process/Process.php(679): Symfony\\Component\\Process\\Process->readPipesForOutput('getErrorOutput')
#2 /var/www/homolog-ws-sts.midia.zone/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(67): Symfony\\Component\\Process\\Process->getErrorOutput()
#3 /var/www/homolog-ws-sts.midia.zone/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\\BinaryDriver\\ProcessRunner->run(Object(Symfony\\Component\\Process\\Process), Object(SplObjectStorage), false)
#4 /var/www/homolog-ws-sts.midia.zone/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\\BinaryDriver\\AbstractBinary->run(Object(Symfony\\Component\\Process\\Process), false, NULL)
#5 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\\BinaryDriver\\AbstractBinary->command(Array)
#6 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(43): FFMpeg\\FFProbe\\OptionsTester->retrieveHelpOutput()
#7 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(237): FFMpeg\\FFProbe\\OptionsTester->has('-show_streams')
#8 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(206): FFMpeg\\FFProbe->probe('/var/www/homolo...', '-show_streams', 'streams')
#9 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(95): FFMpeg\\FFProbe->streams('/var/www/homolo...')
#10 /var/www/homolog-ws-sts.midia.zone/vendor/lakshmaji/thumbnail/src/Thumbnail.php(68): FFMpeg\\FFMpeg->open('/var/www/homolo...')`

**Comment by danieltrolezi** [comment]
Same thing here... My stacktrace:

`
/vendor/lakshmaji/thumbnail/src/[2020-08-11 12:48:20] homolog.ERROR: Process must be started before calling "getErrorOutput()". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\LogicException(code: 0): Process must be started before calling \"getErrorOutput()\". at /var/www/homolog-ws-sts.midia.zone/vendor/symfony/process/Process.php:1569

#0 /var/www/homolog-ws-sts.midia.zone/vendor/symfony/process/Process.php(1365): Symfony\\Component\\Process\\Process->requireProcessIsStarted('getErrorOutput')

#1 /var/www/homolog-ws-sts.midia.zone/vendor/symfony/process/Process.php(679): Symfony\\Component\\Process\\Process->readPipesForOutput('getErrorOutput')

#2 /var/www/homolog-ws-sts.midia.zone/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(67): Symfony\\Component\\Process\\Process->getErrorOutput()

#3 /var/www/homolog-ws-sts.midia.zone/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\\BinaryDriver\\ProcessRunner->run(Object(Symfony\\Component\\Process\\Process), Object(SplObjectStorage), false)

#4 /var/www/homolog-ws-sts.midia.zone/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\\BinaryDriver\\AbstractBinary->run(Object(Symfony\\Component\\Process\\Process), false, NULL)

#5 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(61): Alchemy\\BinaryDriver\\AbstractBinary->command(Array)

#6 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe/OptionsTester.php(43): FFMpeg\\FFProbe\\OptionsTester->retrieveHelpOutput()

#7 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(237): FFMpeg\\FFProbe\\OptionsTester->has('-show_streams')

#8 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(206): FFMpeg\\FFProbe->probe('/var/www/homolo...', '-show_streams', 'streams')

#9 /var/www/homolog-ws-sts.midia.zone/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(95): FFMpeg\\FFProbe->streams('/var/www/homolo...')

#10 /var/www/homolog-ws-sts.midia.zone/vendor/lakshmaji/thumbnail/src/Thumbnail.php(68): FFMpeg\\FFMpeg->open('/var/www/homolo...')
`

**Comment by zazoomauro** [comment]
@danieltrolezi having the same issue here! do you know how ti fix it?

**Comment by GT-remix** [comment]
look your php.ini    open_basedir =    ,

**Comment by GT-remix** [comment]
open_basedir =   (this is point to resolve the problem)，   you can dump  at ProcessRunner.php  line 67   ,dump the $e,  and  then you will find the reason

**Comment by GT-remix** [comment]
> @danieltrolezi having the same issue here! do you know how to fix it?

look  my answer

**Comment by TheRealMattLear** [comment]
I'm seeing this when fetching information about the stream. I can see that ffprobe is running quickly and suspect that it might be finishing too quickly for the Symfony Process. Any suggestions?

**Comment by cyberpunkbln** [comment]
Hello,
i have the same problem, but i have set open_basedir + getenv('TEMP'). I have a very restricted open_basedir setting. Give it a chance that i can set the temp to inside my project? I mean 'temporary_directory' => '/inside/my/project' doesnt resolve this problem??

**Comment by stevebauman** [comment]
This is still an issue. `$process->getErrorOutput()` is being called potentially before the process started, so the process needs to be checked before outputting the error output:

https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/5e7b15710a8607e8a3a2d9fbe2c150a99b924fa5/src/Alchemy/BinaryDriver/ProcessRunner.php#L63-L69

**Comment by hebertlima** [comment]
any fix?

**Comment by aogg** [comment]
+1

**Comment by OMKE** [comment]
+1
