### ISSUE TITLE
Strict autoloaders cause unavailable Symfony file to throw exception

### ISSUE THREAD

**Issue by StrikeAgainst** [PHP-FFMpeg/PHP-FFMpeg#689]
| Q              | A
| -------------- | ---
| Bug?           | yes
| New Feature?   | no
| Version Used   | v0.14 (according to composer.lock)
| FFmpeg Version | 4.1-11
| OS             | Linux version 4.4.59+ (running on a Synology DS218play)

#### Actual Behavior

Whenever I try to run `FFMpeg::create()`, I get this Exception thrown:

> Warning: Uncaught ErrorException: init.php:15 - require_once(/volume1/web/class/Symfony/Component/Process/ProcessBuilder.php): failed to open stream: No such file or directory (2) in /volume1/web/init.php:5
Stack trace:
#0 /volume1/web/init.php(15): {closure}(2, 'require_once(/v...', '/volume1/we...', 15, Array)
#1 /volume1/web/init.php(15): require_once()
#2 [internal function]: {closure}('Symfony\\Compone...')
#3 [internal function]: spl_autoload_call('Symfony\\Compone...')
#4 /volume1/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessBuilderFactory.php(182): method_exists('Symfony\\Compone...', 'setPrefix')
#5 /volume1/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessBuilderFactory.php(62): Alchemy\BinaryDriver\ProcessBuilderFactory->detectEmulation()
#6 /volume1/web/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(172): Alchemy\BinaryDriver\ProcessBuilderFactory->__construct('/bin/ffprobe')
#7 /volume1/web/vendor/php-ffmpeg/ in /volume1/web/init.php on line 5

The exception stems from an autoloader I added myself, but that already means that the missing file couldn't be found by Composer's autoloader. Searching through Symfony's files, I can't find a class called `ProcessBuilder` myself.

#### Expected Behavior

Obviously for the exception not to be thrown and the extension working just fine.

#### Steps to Reproduce

After installing PHP-FFMpeg in my project via composer, adding the FFMpeg package via Synology's DRM Package Manager, copying `ffprobe` to the `/bin` directory, and appending my own autoloader after composer's one, running the code as such gives me the exception:

```
require_once(__DIR__ . '/vendor/autoload.php'); //composers autoloader
require_once(__DIR__ . '/autoload.php'); //my own autoloader

use FFMpeg\FFMpeg;

$ffmpeg = FFMpeg::create([
                'ffmpeg.binaries'  => '/bin/ffmpeg',
                'ffprobe.binaries' => '/bin/ffprobe'
            ]);
```

#### Possible Solutions

Taking out my own autoloader makes it work just fine, I suppose because Composer's autoloader only uses the non-strict `include` for files, while mine uses `require`. I could adapt my autoloader to not throw exceptions as well, although I'd prefer it doing so. Any chance the Symfony dependency for this extension could get fixed instead?

**Comment by edigu** [comment]
Any updates on this?

IMO this is not directly related with autolading. Seems like `alchemy-fr/BinaryDriver` relying on `ProcessBuilder` which does not exist after `symfony/process::v3.4`

Was there an replacement or symfony/composer magic behind the usage of this non-existent class?
