### ISSUE TITLE
Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command

### ISSUE THREAD

**Issue by Dreamred** [PHP-FFMpeg/PHP-FFMpeg#793]
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | "^0.16"
| FFmpeg Version | 2.6.8

#### Actual Behavior

I am getting this error in Linux , can anyone help me ?

`Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command ‘/usr/bin/ffmpeg’ ‘-y’ ‘-i’ ‘/data/25120036_354316fkRk.mp4’ ‘-threads’ ‘6’ ‘-vcodec’ ‘libx264’ ‘-acodec’ ‘aac’ ‘-b:v’ ‘2754k’ ‘-refs’ ‘6’ ‘-coder’ ‘1’ ‘-sc_threshold’ ‘40’ ‘-flags’ ‘+loop’ ‘-me_range’ ‘16’ ‘-subq’ ‘7’ ‘-i_qfactor’ ‘0.71’ ‘-qcomp’ ‘0.6’ ‘-qdiff’ ‘4’ ‘-trellis’ ‘1’ ‘-b:a’ ‘90k’ ‘-strict’ ‘-2’ ‘-bufsize’ ‘2754k’ ‘-maxrate’ ‘2754k’ ‘-vf’ ‘[in]scale=750:1334 [out]’ ‘-pass’ ‘1’ ‘-passlogfile’ ‘/tmp/ffmpeg-passes60123785efb0an3gn3/pass-60123785efbb8’ ‘/data/28120317_24439QGXy3.mp4’:`

`Error Output:`

ffmpeg version 2.6.8 Copyright © 2000-2016 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-16)
  configuration: –prefix=/usr –bindir=/usr/bin –datadir=/usr/share/ffmpeg –incdir=/usr/include/ffmpeg –libdir=/usr/lib64 –mandir=/usr/share/man –arch=x86_64 –optflags=‘-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector –param=ssp-buffer-size=4 -m64 -mtune=generic’ –enable-bzlib –disable-crystalhd –enable-gnutls –enable-ladspa –enable-libass –enable-libdc1394 –enable-libfaac –enable-nonfree –disable-indev=jack –enable-libfreetype –enable-libgsm –enable-libmp3lame –enable-openal –enable-libopenjpeg –enable-libopus –enable-libpulse –enable-libschroedinger –enable-libsoxr –enable-libspeex –enable-libtheora –enable-libvorbis –enable-libv4l2 –enable-libx264 –enable-libx265 –enable-libxvid –enable-x11grab –enable-avfilter –enable-avresample –enable-postproc –enable-pthreads –disable-static –enable-shared –enable-gpl –disable-debug –disable-stripping –shlibdir=/usr/lib64 –enable-runtime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from ‘/data/25120036_354316fkRk.mp4’:
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
  Duration: 00:00:39.70, start: 0.021333, bitrate: 2782 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x1280 [SAR 1:1 DAR 9:16], 2690 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 90 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[libx264 @ 0x192dc60] using SAR=2001/2000
[libx264 @ 0x192dc60] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x192dc60] profile Main, level 3.2
[libx264 @ 0x192dc60] 264 - core 142 r2438 af8e768 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=cbr mbtree=1 bitrate=2754 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=2754 vbv_bufsize=2754 nal_hrd=none filler=0 ip_ratio=1.41 aq=1:1.00
Output #0, mp4, to ‘/data/28120317_24439QGXy3.mp4’:
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
    Stream #0:0(und): Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 750x1334 [SAR 2001:2000 DAR 9:16], q=-1–1, pass 1, 2754 kb/s, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.26.100 libx264
    Stream #0:1(und): Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp, 90 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc56.26.100 aac
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
frame=   39 fps=0.0 q=0.0 size=       0kB time=00:00:01.74 bitrate=   0.2kbits/s dup=1 drop=0    
frame=   51 fps= 46 q=33.0 size=      79kB time=00:00:02.13 bitrate= 304.0kbits/s dup=1 drop=0    
frame=   83 fps= 51 q=22.0 size=     478kB time=00:00:03.20 bitrate=1224.8kbits/s dup=1 drop=0    
frame=  105 fps= 49 q=18.0 size=     628kB time=00:00:03.94 bitrate=1304.4kbits/s dup=1 drop=0    
frame=  118 fps= 45 q=19.0 size=     705kB time=00:00:04.37 bitrate=1321.1kbits/s dup=1 drop=0    
frame=  137 fps= 43 q=18.0 size=     882kB time=00:00:05.01 bitrate=1441.2kbits/s dup=1 drop=0    
frame=  156 fps= 43 q=15.0 size=     988kB time=00:00:05.65 bitrate=1432.3kbits/s dup=1 drop=0    
frame=  171 fps= 41 q=32.0 size=    1211kB time=00:00:06.14 bitrate=1615.2kbits/s dup=1 drop=0    
frame=  183 fps= 38 q=33.0 size=    1407kB time=00:00:06.54 bitrate=1760.3kbits/s dup=1 drop=0    
frame=  205 fps= 39 q=32.0 size=    1600kB time=00:00:07.27 bitrate=1801.5kbits/s dup=1 drop=0    
frame=  226 fps= 39 q=36.0 size=    1878kB time=00:00:07.97 bitrate=1928.6kbits/s dup=1 drop=0    
frame=  247 fps= 39 q=36.0 size=    2076kB time=00:00:08.68 bitrate=1959.0kbits/s dup=1 drop=0    
frame=  269 fps= 39 q=36.0 size=    2334kB time=00:00:09.40 bitrate=2032.1kbits/s dup=1 drop=0    
frame=  283 fps= 38 q=36.0 size=    2518kB time=00:00:09.87 bitrate=2088.3kbits/s dup=1 drop=0    
frame=  299 fps= 38 q=34.0 size=    2745kB time=00:00:10.41 bitrate=2160.4kbits/s dup=1 drop=0    
frame=  317 fps= 37 q=35.0 size=    3008kB time=00:00:11.00 bitrate=2238.2kbits/s dup=1 drop=0    
frame=  345 fps= 38 q=31.0 size=    3252kB time=00:00:11.94 bitrate=2229.6kbits/s dup=1 drop=0    
frame=  362 fps= 38 q=24.0 size=    3439kB time=00:00:12.50 bitrate=2253.6kbits/s dup=1 drop=0    
frame=  382 fps= 38 q=29.0 size=    3524kB time=00:00:13.18 bitrate=2189.6kbits/s dup=1 drop=0    
frame=  406 fps= 38 q=28.0 size=    3849kB time=00:00:13.97 bitrate=2256.6kbits/s dup=1 drop=0    
frame=  429 fps= 38 q=23.0 size=    4027kB time=00:00:14.74 bitrate=2237.9kbits/s dup=1 drop=0    
frame=  454 fps= 39 q=32.0 size=    4361kB time=00:00:15.57 bitrate=2293.8kbits/s dup=1 drop=0    
frame=  476 fps= 39 q=33.0 size=    4611kB time=00:00:16.32 bitrate=2314.5kbits/s dup=1 drop=0    
frame=  499 fps= 39 q=34.0 size=    4918kB time=00:00:17.06 bitrate=2360.7kbits/s dup=1 drop=0    
frame=  526 fps= 40 q=33.0 size=    5235kB time=00:00:17.98 bitrate=2384.8kbits/s dup=1 drop=0    
frame=  552 fps= 40 q=33.0 size=    5510kB time=00:00:18.83 bitrate=2396.2kbits/s dup=1 drop=0    
frame=  573 fps= 40 q=32.0 size=    5699kB time=00:00:19.54 bitrate=2389.3kbits/s dup=1 drop=0    
frame=  595 fps= 40 q=33.0 size=    6120kB time=00:00:20.26 bitrate=2473.7kbits/s dup=1 drop=0    
frame=  613 fps= 40 q=32.0 size=    6269kB time=00:00:20.88 bitrate=2459.0kbits/s dup=1 drop=0    
frame=  634 fps= 40 q=29.0 size=    6444kB time=00:00:21.56 bitrate=2447.6kbits/s dup=1 drop=0    
frame=  658 fps= 40 q=27.0 size=    6621kB time=00:00:22.37 bitrate=2423.8kbits/s dup=1 drop=0    
frame=  685 fps= 41 q=28.0 size=    6862kB time=00:00:23.27 bitrate=2415.2kbits/s dup=1 drop=0    
frame=  707 fps= 41 q=30.0 size=    7137kB time=00:00:23.97 bitrate=2438.2kbits/s dup=1 drop=0    
frame=  726 fps= 41 q=31.0 size=    7318kB time=00:00:24.64 bitrate=2433.1kbits/s dup=1 drop=0    
frame=  748 fps= 41 q=32.0 size=    7663kB time=00:00:25.38 bitrate=2472.7kbits/s dup=1 drop=0    
frame=  776 fps= 41 q=31.0 size=    8003kB time=00:00:26.32 bitrate=2490.3kbits/s dup=1 drop=0    
frame=  797 fps= 41 q=31.0 size=    8221kB time=00:00:26.98 bitrate=2495.5kbits/s dup=1 drop=0    
frame=  819 fps= 41 q=31.0 size=    8450kB time=00:00:27.73 bitrate=2496.0kbits/s dup=1 drop=0    
frame=  842 fps= 41 q=29.0 size=    8675kB time=00:00:28.50 bitrate=2493.3kbits/s dup=1 drop=0    
frame=  871 fps= 42 q=28.0 size=    8982kB time=00:00:29.48 bitrate=2495.6kbits/s dup=1 drop=0    
frame=  894 fps= 42 q=31.0 size=    9152kB time=00:00:30.25 bitrate=2478.5kbits/s dup=1 drop=0    
frame=  914 fps= 42 q=31.0 size=    9461kB time=00:00:30.91 bitrate=2507.1kbits/s dup=1 drop=0    
frame=  935 fps= 42 q=32.0 size=    9749kB time=00:00:31.61 bitrate=2526.0kbits/s dup=1 drop=0    
frame=  954 fps= 41 q=31.0 size=    9966kB time=00:00:32.23 bitrate=2532.6kbits/s dup=1 drop=0    
frame=  980 fps= 42 q=31.0 size=   10283kB time=00:00:33.10 bitrate=2544.1kbits/s dup=1 drop=0    
frame= 1009 fps= 42 q=29.0 size=   10608kB time=00:00:34.06 bitrate=2550.6kbits/s dup=1 drop=0    
frame= 1035 fps= 42 q=24.0 size=   10782kB time=00:00:34.94 bitrate=2527.7kbits/s dup=1 drop=0    
frame= 1062 fps= 42 q=24.0 size=   11162kB time=00:00:35.84 bitrate=2551.3kbits/s dup=1 drop=0    
frame= 1088 fps= 42 q=23.0 size=   11348kB time=00:00:36.71 bitrate=2532.0kbits/s dup=1 drop=0    
frame= 1108 fps= 42 q=28.0 size=   11642kB time=00:00:37.37 bitrate=2551.6kbits/s dup=1 drop=0    
frame= 1133 fps= 42 q=27.0 size=   11836kB time=00:00:38.20 bitrate=2537.8kbits/s dup=1 drop=0    
frame= 1152 fps= 42 q=28.0 size=   11990kB time=00:00:38.84 bitrate=2528.4kbits/s dup=1 drop=0    
frame= 1170 fps= 42 q=29.0 size=   12174kB time=00:00:39.44 bitrate=2528.4kbits/s dup=1 drop=0    
frame= 1187 fps= 42 q=31.0 size=   12434kB time=00:00:39.65 bitrate=2568.5kbits/s dup=1 drop=0    
frame= 1189 fps= 41 q=-1.0 Lsize=   13164kB time=00:00:39.70 bitrate=2716.3kbits/s dup=1 drop=0
video:12683kB audio:439kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.323345%
[libx264 @ 0x192dc60] frame I:8     Avg QP:21.38  size: 88322
[libx264 @ 0x192dc60] frame P:617   Avg QP:26.76  size: 16580
[libx264 @ 0x192dc60] frame B:564   Avg QP:29.06  size:  3634
[libx264 @ 0x192dc60] consecutive B-frames: 22.3% 38.5% 14.6% 24.6%
[libx264 @ 0x192dc60] mb I  I16..4: 34.5%  0.0% 65.5%
[libx264 @ 0x192dc60] mb P  I16..4: 22.6%  0.0%  0.0%  P16..4: 38.8%  0.0%  0.0%  0.0%  0.0%    skip:38.6%
[libx264 @ 0x192dc60] mb B  I16..4:  2.3%  0.0%  0.0%  B16..8: 14.9%  0.0%  0.0%  direct: 3.7%  skip:79.0%  L0:33.2% L1:52.8% BI:14.0%
[libx264 @ 0x192dc60] coded y,uvDC,uvAC intra: 32.3% 48.1% 12.6% inter: 10.5% 11.8% 0.7%
[libx264 @ 0x192dc60] i16 v,h,dc,p: 30% 38% 20% 12%
[libx264 @ 0x192dc60] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 26% 12%  8%  7%  5%  6%  7%  7%
[libx264 @ 0x192dc60] i8c dc,h,v,p: 48% 29% 17%  6%
[libx264 @ 0x192dc60] Weighted P-Frames: Y:0.3% UV:0.0%
[libx264 @ 0x192dc60] kb/s:2621.27
` in /data/web/framework/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:95
Stack trace:
#0 /data/web/framework/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(73): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure(“/usr/bin/ffmpe…‘, ‘ffmpeg version …’)
#1 /data/web/framework/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false)
#2 /data/web/framework/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array)
#3 /data/web/framework/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php(96): Alchemy\BinaryDriver\AbstractBinary->command(Array, false, Array)`

From the error output, it looks like it has been completed and the output file[28120317_24439QGXy3.mp4] is also generated.

And when I paste it in terminal, the command works!

#### Expected Behavior

please don't throw the exception..

#### Steps to Reproduce

It seems occasionally?

**Comment by zykyan** [comment]
Same issue. Any solutions ?

**Comment by spider4216** [comment]
the same :(
