### ISSUE TITLE
unable to load ffprobe

### ISSUE THREAD

**Issue by deadpool8426** [PHP-FFMpeg/PHP-FFMpeg#820]
| Q              | A
| -------------- | ---
| Bug?           | unable to load ffprobe
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | v0.18.0
| OS             | Windows 10

#### Actual Behavior

![image](https://user-images.githubusercontent.com/75540373/121097591-d8122880-c811-11eb-9fe5-f01c276147bf.png)

#### Expected Behavior

I want to generate a video thumbnail image for preview.

#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/75540373/121097487-abf6a780-c811-11eb-9fe2-d9854d18a203.png)

**Comment by savire** [comment]
Yeah it happen to me too on Ubuntu  Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)

FFMPEG installed properly from source following the doc listed here : 

https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

Executing FFMPEG and FFPROBE is working.

`ffmpeg
ffmpeg version N-102967-g3f5d5c1c2d Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/root/bin --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libdav1d --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  3.101 / 59.  3.101
  libavformat    59.  4.100 / 59.  4.100
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.103 /  8.  0.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

`ffprobe
ffprobe version N-102967-g3f5d5c1c2d Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/root/bin --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libdav1d --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      57.  0.100 / 57.  0.100
  libavcodec     59.  3.101 / 59.  3.101
  libavformat    59.  4.100 / 59.  4.100
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.103 /  8.  0.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

You have to specify one input file.
Use -h to get full help or, even better, run 'man ffprobe'.
`
PHP Code 
`
<?php
require_once('vendor/autoload.php');

try {
	
	FFMpeg\FFMpeg::create(
		array(
			'ffmpeg.binaries'  => '/PATH/ffmpeg',
			'ffprobe.binaries' => '/PATH/ffprobe',
		)
	);
} catch (Exception $e) {
	echo $e->getMessage();
}
`

**Comment by mamislimen** [comment]
Same issue. Any solutions ?

**Comment by husen-hn** [comment]
same issue.
```
Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, 
ffprobe in /websites/default/vendor/php-ffmpeg/php-ffmpeg/src/Alchemy/BinaryDriver/AbstractBinary.php:159 Stack trace: #0 
/websites/default/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver
\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration)) #1 /websites/default/vendor/php-ffmpeg/php-
ffmpeg/src/FFMpeg/FFProbe.php(220): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), 
NULL) #2 /websites/default/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(130): FFMpeg\FFProbe::create(Array, 
NULL, Object(Symfony\Component\Cache\Adapter\ArrayAdapter)) #3 /websites/default/public/index.php(29): 
FFMpeg\FFMpeg::create() #4 {main} Next FFMpeg\Exception\ExecutableNotFoundException: Unable to load FFProbe in 
/websites/default/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php:50 Stack trace: #0 /websites/default
/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(220): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy
\BinaryDriver\Configuration), NULL) #1 /websites/default/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(130): 
FFMpeg\FFProbe::create(Array, NULL, Object(Symfony\Component\Cache\Adapter\ArrayAdapter)) #2 /websites/default/public
/index.php(29): FFMpeg\FFMpeg::create() #3 {main}
```

**Comment by Ramdeep-zentral** [comment]
Same issue - Unable to load FFProbe

**Comment by angelomelonas** [comment]
I am also currently experience this issue. It works fine if I run `ffmpeg` using `system('ffmpeg -i...');`, but not using `php-ffmpeg`.
